name: Bump version
description: Bump workspace version

inputs:
  version:
    type: string
    required: true
  preid:
    type: string
    default: ''
    required: false

outputs:
  version:
    description: Outputed version
    value: ${{ steps.version.outputs.version }}
  json_version:
    description: Json version
    value: ${{ steps.bump-ver.outputs.json_version || steps.bump-pre.outputs.json_version }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Bump Version
      id: bump-ver
      if: inputs.preid == ''
      run: |
        npm -ws version ${{ inputs.version }} -m"ci(version): bump to v%s"
        json_version=$(npm version)
        ${{ fromJson('$json_version') }}
      shell: bash

    - name: Bump Pre Version
      id: bump-pre
      if: inputs.preid != ''
      run: |
        npm version ${{ inputs.version }} --preid=${{ inputs.preid }} -m"ci(version): bump to v%s"
        json_version=$(npm version)
        ${{ fromJson("$json_version") }}
      shell: bash
