name: release

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "Cheese Grinder CI"
          git config user.email "<>"


      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Bump Version
        id: bump-ver
        run: |
          npm -ws version patch -m"ci(version): bump to v%s"
          json_version=$(npm version)
          ${{ fromJson('json_version') }}

      # - name: Bump version
      #   id: bump
      #   uses: ./.github/workflows/actions/bump
      #   with:
      #     version: patch
